version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
        - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=balta
      - MONGO_INITDB_ROOT_PASSWORD=e296cd9f
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
        - rabbitmq_go_net

  api-identidade:
        image: cadastro-api:latest
        container_name: Cadastro-API 
        build: 
            dockerfile: ./Cadastro-API/Cadastro-API/Dockerfile  
        restart: always    
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5101;http://+5102
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        
  api-carrinho:
        image: delivery.email:latest
        container_name: Delivery.Email
        build: 
            dockerfile: ./Delivery.Email/Delivery.Email/Dockerfile      
        restart: always             
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5201;http://+5202
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro

networks:
  rabbitmq_go_net:
    driver: bridge

